### ISSUE TITLE
Instantiating TempiFFT

### ISSUE THREAD

**Issue by AlexanderHearX** [jscalo/tempi-fft#10]
There's an assert failure "Size must be a power of 2" when instantiating the FFT. inSize is 341, how would I go about checking where the problem is originating from?

**Comment by Crittar** [comment]
Have you checked the viewDidLoad() of SpectralViewController? I think that’s where the TemiAudioUnit is instantiated.

**Comment by AlexanderHearX** [comment]
It ended up working, I had to do a calibration first

**Comment by nebucaz** [comment]
Can not get this working, frame size is always 470 or 471. Can you give me a hint on that - what do you mean with "calibration"?

**Comment by Bcow7** [comment]
Hello @nebucaz 
I have the same frame size issue. Did you solve it?
