### ISSUE TITLE
About FFT complex forward

### ISSUE THREAD

**Issue by muga87** [jscalo/tempi-fft#16]
1.	I need to calculate Complex FFT values in my project using array of doubles using recorded buffer values.
	2.	Using tempFFT we are passing array fo floats and getting array of floats after fft calculation, I am using below code

		       let fft_1d = TempiFFT_Old(withSize: Int(Float(2*windowSize)), sampleRate: Float(sampleRate))

 			rowFFT =  fft_1d.fftForward(inMonoBuffer: rowFFT)
		
	Here, rowFFT  =  Array of doubles, I am passing values like
  - 0 : -0.0
  - 1 : 0.0
  - 2 : -5.3642644e-08
  - 3 : 0.0
  - 4 : -1.6688783e-07
  - 5 : 0.0
  - 6 : 3.360723e-08
  - 7 : 0.0
  - 8 : 5.3311686e-07
  - 9 : 0.0
  - 10 : 6.3551335e-07
  - 11 : 0.0
  - 12 : -1.6027724e-07
	
	I am getting following values after fftForward method,
  - 0 : 0.0008335819
  - 1 : 0.000416955
  - 2 : 0.00040760144
  - 3 : 0.00037687368
  - 4 : 0.00023080478
  - 5 : 0.00017511273
  - 6 : 1.41498995e-05
  - 7 : 0.004414823
  - 8 : 0.011066418
  - 9 : 0.0018234459
  - 10 : 0.0047750766
  - 11 : 0.010834914
  - 12 : 0.05561675
	
  3. But, in android we are using DoubleFFt_1D, the fft values are completely different.
DoubleFFT_1D fft_1d = new DoubleFFT_1D(windowSize);
double[] rowFFT = new double[2 * windowSize];
 
for (int win = 0; win < windowSize; win++)
{
rowFFT[win * 2] = sample[win + time * (windowSize - overlap)] * windowing[win];
rowFFT[win * 2 + 1] = 0;
}
After above loop execution rowFFT array has got 4096 values. Then we have below FFT method for complex forward
fft_1d.complexForward(rowFFT);
 
In Android post execution of above method rowFFT values will change and still I have 4096 values. But in iOS up to 2047 index we have got values and rest all are zero 
	
  4. Am I did anything wrong, can you suggest me if anything want to add.

**Comment by jscalo** [comment]
I'm really sorry but this project doesn't come with technical support. You might try https://math.stackexchange.com .
