### ISSUE TITLE
Strange values when working on octave

### ISSUE THREAD

**Issue by kvacquier** [jscalo/tempi-fft#4]
Hello. i'm trying to use it with bands per octave but i have a very strange result. any idea of why ?

![img_1054](https://cloud.githubusercontent.com/assets/4428155/25005739/5e77d258-205a-11e7-9229-a55b17c7a2f0.PNG)

I've change the line to : 		fft.calculateLogarithmicBands(minFrequency: 20, maxFrequency: 20000, bandsPerOctave: 7)

(all small values are "grouped" and it's precise only when in high range) please don't care of the bottom label

**Comment by jscalo** [comment]
You're seeing this in the sample app, right? If so it's because the labels in the sample app are drawn assuming a linear distribution. If you use logarithmic instead, you'd have to change how the labels are placed. Can you use `fft.calculateLinearBands()` instead?

**Comment by kvacquier** [comment]
When i use fft.calculateLinearBands i only have the two first bands that cause problems (between 20 and 200). I would like to use it to detect bass pulse so that's a bit annoying (bass notes are between 40hz and 400hz)

Edit : Founded why : iPad microphone sucks in bass frequencies : 
![screen shot 2017-04-18 at 15 22 49](https://cloud.githubusercontent.com/assets/4428155/25132766/eae5cf4e-244a-11e7-8b51-5e83a1cb9a00.png)

**Comment by jscalo** [comment]
Ha yeah that would explain it 😀 There are some decent inexpensive mics you can get that might help.
