### ISSUE TITLE
Playback live stream url example

### ISSUE THREAD

**Issue by iDevelopper** [jscalo/tempi-fft#5]
Great job!

Could you provide a sample for play a stream URL (ex: http://streaming.shoutcast.com/cooljazzflorida?lang=en ) instead of recording the micro?

Or just an How to do small guide?

Thanks in advance.

Best Regards,

**Comment by jscalo** [comment]
TempiFFT works on raw audio samples and doesn't really care where they come from. So when you get your audio data from the stream, just stuff them in the buffer sent to `fftForward`.
