### ISSUE TITLE
hamming and hanning window types reversed in fftFoward

### ISSUE THREAD

**Issue by muzzleburst** [jscalo/tempi-fft#8]
Howdy,
Thanks so much for contributing this library!

While reading through it, it looks like the fftForward function in TempiFFT/TempiFFT.swift lines 133-136, in the master branch, has the hamming and hanning switch cases reversed. When the case is .hamming, the vDSP_hann_window function is called, and when the case is .hanning, the vDSP_hamm_window function is called.

See the following link to the source code:
https://github.com/jscalo/tempi-fft/blob/master/TempiFFT/TempiFFT.swift#L133

Is this expected?

Thank you!
-Robert

**Comment by jscalo** [comment]
Good catch! It's almost a cruel joke that these two guys' names were so close together. (I know, one was Hann, but still!)
